### ISSUE TITLE
onClose called without check for existence, not marked as required

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-modal#103]
In the `frost-modal-binding` component, the `onClose` is [not marked as a required property](https://github.com/ciena-frost/ember-frost-modal/blob/v6.2.6/addon/components/frost-modal-binding.js#L36) it [does not have a default value set](https://github.com/ciena-frost/ember-frost-modal/blob/v6.2.6/addon/components/frost-modal-binding.js#L40-L46) and it is [called without a check for its existence](https://github.com/ciena-frost/ember-frost-modal/blob/v6.2.6/addon/components/frost-modal-binding.js#L69) (also [here](https://github.com/ciena-frost/ember-frost-modal/blob/v6.2.6/addon/components/frost-modal-binding.js#L78), and [here](https://github.com/ciena-frost/ember-frost-modal/blob/v6.2.6/addon/components/frost-modal-binding.js#L84). 

As a result, a consumer can instantiate a `{{frost-modal-binding}}` (or one of the components that derives from it, like `frost-modal-form`, leave off the `onClose`, receive no `propTypes` warning about it being required and missing, and get javascript exceptions when the component tries to call a function that does not exist.

We should do one of the following to rectify this situation:

1. Mark `onClose` as required in the `propTypes` definition
2. Provide a default empty function for `onClose` in `getDefaultProps()`
3. Add a check around all calls to `onClose` to make sure it exists first.

I'm not a big fan of 3 personally, I'd much prefer 1 or 2, probably 2, since all functionality can be achieved without an `onClose` function by toggling the `isVisible` based on other conditions and responding to `onConfirm` and `onCancel` (which probably should be marked as required, or provided defaults as well so we don't need the guards around calling them).

**Comment by sglanzer-fire** [comment]
`onClose` used to be required, I can't remember why it changed.  Considering that it's a breaking change to make it required, I'd probably be most comfortable with #2, but still documenting it as the general path most devs would take.

**Comment by job13er** [comment]
@sglanzer I'm not sure it would be a breaking change. Technically it's required now, it's throwing a javascript error when it's not provided, so marking it as required in `propTypes` would really just be better documentation of existing functionality.

**Comment by sglanzer-fire** [comment]
@job13er fair point - `onCancel` actually calls `onClose` https://github.com/ciena-frost/ember-frost-modal/blob/master/addon/components/frost-modal-binding.js#L69 so I'd probably go with option 1 then
