### ISSUE TITLE
GitHub pages documentation is not accessible

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-modal#114]
http://ciena-frost.github.io/ember-frost-modal

**Comment by EWhite613** [comment]
Look's like the [gh-pages branch](https://github.com/ciena-frost/ember-frost-modal/tree/gh-pages) is empty, and the last commit removed everything but didn't add the new files that should've been created

**Comment by rox163** [comment]
Manually pushed the latest version on the gh-pages branch and the demo is back up. Will hav to keep an eye on this for the next PR.

**Comment by EWhite613** [comment]
Looks like a PR broke the demo page again

**Comment by EWhite613** [comment]
Due to failed build during publish of gh-pages
https://travis-ci.org/ciena-frost/ember-frost-modal/jobs/269655099#L2327

**Comment by rox163** [comment]
this addon doesnt use ember-css-modules...hmm
