### ISSUE TITLE
Safari: The closing button is not visible for the about dialog

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-modal#65]
Safari
![screen shot 2016-11-29 at 12 00 30 pm](https://cloud.githubusercontent.com/assets/18552536/20719928/780f86c8-b62b-11e6-96e6-8b20c659dfc9.png)

**Comment by dafortin** [comment]
Chrome
![screen shot 2016-11-29 at 11 59 52 am](https://cloud.githubusercontent.com/assets/18552536/20719937/7e7f4ff2-b62b-11e6-83ea-060c4ede43e0.png)

**Comment by notmessenger** [comment]
Closed because we only currently support Chrome and Firefox.
