### ISSUE TITLE
Safari: Content of the page get shifted on the right when modal is open

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-modal#66]
This problem is occurring only in 'Remote outlet' route in the demo.

**Comment by dafortin** [comment]
Safari
![screen shot 2016-11-29 at 12 02 36 pm](https://cloud.githubusercontent.com/assets/18552536/20720021/c289dcda-b62b-11e6-9690-15e27eb0d0e6.png)

**Comment by dafortin** [comment]
Chrome
![screen shot 2016-11-29 at 12 02 25 pm](https://cloud.githubusercontent.com/assets/18552536/20720028/c81e9a00-b62b-11e6-939a-96ee5411f6a9.png)

**Comment by notmessenger** [comment]
Closed because we only currently support Chrome and Firefox.
