### ISSUE TITLE
Clean install. Build do not work

### ISSUE THREAD

**Issue by Kamaz87** [ciena-frost/ember-frost-modal#69]
versions:
ember-cli: 2.8.0
node: 6.9.2
os: win32 x64

**ember new operator**
**ember install ember-frost-modal**
**ember build** with error:

> Build failed.
> The Broccoli Plugin: [SvgProcessor: SVGStore Processor] failed with:
> Error: Path must be absolute: "D:\work\operator\tmp\svg_processor-output_path-qEiI99BP.tmp"
>     at Object.assertAbsolutePaths (D:\work\operator\node_modules\broccoli-kitchen-sink-helpers\index.js:174:13)
>     at SvgProcessor.build (D:\work\operator\node_modules\ember-frost-core\node_modules\broccoli-svgstore\index.js:86:11)
>     at D:\work\operator\node_modules\broccoli-caching-writer\index.js:149:21
>     at tryCatch (D:\work\operator\node_modules\rsvp\dist\rsvp.js:538:12)
>     at invokeCallback (D:\work\operator\node_modules\rsvp\dist\rsvp.js:553:13)
>     at publish (D:\work\operator\node_modules\rsvp\dist\rsvp.js:521:7)
>     at flush (D:\work\operator\node_modules\rsvp\dist\rsvp.js:2373:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> 
> The broccoli plugin was instantiated at:
>     at SvgProcessor.Plugin (D:\work\operator\node_modules\broccoli-plugin\index.js:10:31)
>     at SvgProcessor.CachingWriter [as constructor] (D:\work\operator\node_modules\broccoli-caching-writer\index.js:18:10)
>     at new SvgProcessor (D:\work\operator\node_modules\ember-frost-core\node_modules\broccoli-svgstore\index.js:41:17)
>     at Object.keys.map (D:\work\operator\node_modules\ember-frost-core\index.js:191:14)
>     at Array.map (native)
>     at CoreObject.treeForPublic (D:\work\operator\node_modules\ember-frost-core\index.js:181:50)
>     at CoreObject._treeFor (D:\work\operator\node_modules\ember-cli\lib\models\addon.js:371:33)
>     at CoreObject.treeFor (D:\work\operator\node_modules\ember-cli\lib\models\addon.js:339:21)
>     at D:\work\operator\node_modules\ember-cli\lib\broccoli\ember-app.js:498:20
>     at Array.map (native)
> 
> 

What am I doing wrong?

**Comment by sglanzer-fire** [comment]
Looks like a downstream issue with broccoli-svgstore, we'll look into it

**Comment by sibijohn72** [comment]
Same issue here :
https://github.com/ciena-frost/ember-frost-tabs/issues/57

**Comment by chetansingh1987** [comment]
I am Facing the  same issue when i try to complete the frost bunsen tutorial https://github.com/ciena-frost/bunsen-tutorial

**Comment by notmessenger** [comment]
This will be evaluated in #123

**Comment by juwara0** [comment]
This issue was evaluated during https://github.com/ciena-frost/ember-frost-modal/issues/123 with the changes in PR: https://github.com/ciena-frost/ember-frost-modal/pull/129 and the issue was no longer reproducible.
