### ISSUE TITLE
Could not find module `ember-spread`

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-modal#73]
I did a clone of this project, `npm install`, `bower install` and then `ember serve` which resulted in a missing dependency of ember-spread message.

`Could not find module `ember-spread` imported from `ember-frost-core/components/frost-component`

Manually, running `ember generate ember-frost-core` resulted in `ember-spread` being installed and `ember serve` working as expected.

**Comment by sglanzer-fire** [comment]
This should be an issue against `core`, we need to move `spread` into the npm dependencies since I don't believe it requires a blueprint to be executed

**Comment by juwara0** [comment]
I opened this issue here so that the modal's package.json would be updated with `ember-spread`.

What needs to happen on this issue is:
1. Run the `ember-frost-core` generator
2. commit the updated `package.json` that now has `ember-spread` added.

**Comment by sglanzer-fire** [comment]
Spread shouldn't need to be in the devdependencies if core has it in the dependencies - spread would only need to be included here if the modal itself implemented spread

**Comment by juwara0** [comment]
Alright, I understand the direction you are wanting to go. In that case, we need to move `ember-spread` to a dependency in `frost-core`. https://github.com/ciena-frost/ember-frost-core/blob/master/package.json#L63.

This issue can be closed and opened against `frost-core`.
