### ISSUE TITLE
ember-getowner-polyfill deprecation message

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/ember-frost-modal#81]
### Problem
The following deprecation message is being thrown in the console:

```
DEPRECATION: ember-getowner-polyfill is now a true polyfill. 
Use Ember.getOwner directly instead of importing from 
ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
```

### Solution
Investigate removal of `ember-getowner-polyfill` dependency. Is it no longer needed as the deprecation message indicates?

**Comment by job13er** [comment]
I've been trying to track down all of these, I think `liquid-fire` is one culprit that is still importing from `ember-getowner-pollyfill` instead of just installing it. Not sure that there's anything to do in this repo, except maybe update a dependency that's ultimately pulling in `liquid-fire`

**Comment by rox163** [comment]
No longer seeing this issue after other dependency upgrades have completed.
