### ISSUE TITLE
Duplicate about dialogs?

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-modal#91]
It seems this addon is publishing two different about dialogs `frost-modal-about` and `frost-modal-about-dialog`. Based on the dummy app, it appears `frost-modal-about` is the one to use, it's defined in `addon/components/dialogs/about` whereas `frost-modal-about-dialog` is defined at `addon/components/frost-modal-about-dialog`.

Are we really supposed to have two of these? Can we delete one?

**Comment by job13er** [comment]
Nevermind, it appears `frost-modal-about` is actually using `frost-modal-about-dialog`
https://github.com/ciena-frost/ember-frost-modal/blob/master/addon/components/dialogs/about.js#L39

That's a little confusing... I wonder how we make that clearer to people looking at the repo. 

Any ideas?

**Comment by sglanzer-fire** [comment]
Yeah, I struggled a bit with the naming of the wrapper providing the binding config versus the actual dialog.  I'll revisit, maybe even just an architecture.md would be useful
